/**
 * Catálogo OneRio — atrações cobradas do Rio de Janeiro.
 * Preços em centavos (money), aproximados a referências públicas 2025/2026
 * para demo; confirmar com parceiros antes de produção.
 *
 * Categorias:
 * - icone: cartões-postais / mirantes
 * - museu: museus e cultura
 * - familia: aquário, zoológico, natureza
 * - esporte: estádios / tours
 * - cinema: sessões de cinema
 */
import type { Partner } from "@/features/partners/types";
import type { Attraction, TicketType } from "@/features/attractions/types";
import type { Product } from "@/features/catalog/types";
import { money } from "@/features/shared/types";

const NOW = "2026-01-01T00:00:00.000Z";
export const catalogTs = { createdAt: NOW, updatedAt: NOW };
const img = (url: string, alt: string) => ({ url, alt });

export const catalogPartners: Partner[] = [
  // —— Ícones ——
  {
    id: "partner-corcovado",
    name: "Trem do Corcovado",
    slug: "trem-do-corcovado",
    defaultStrategy: "API",
    integration: { adapterKey: "generic-rest", config: { baseUrl: "https://api.parceiro.example" } },
    commissionBps: 1200,
    contactEmail: "operacao@corcovado.example",
    isActive: true,
    ...catalogTs,
  },
  {
    id: "partner-pao",
    name: "Bondinho Pão de Açúcar",
    slug: "pao-de-acucar",
    defaultStrategy: "API",
    integration: { adapterKey: "generic-rest", config: { baseUrl: "https://api.bondinho.example" } },
    commissionBps: 1000,
    contactEmail: "parceiros@bondinho.example",
    isActive: true,
    ...catalogTs,
  },
  {
    id: "partner-yupstar",
    name: "Yup Star Rio",
    slug: "yup-star",
    defaultStrategy: "MANUAL",
    integration: { adapterKey: "manual", config: {} },
    commissionBps: 1400,
    contactEmail: "bilheteria@yupstar.example",
    isActive: true,
    ...catalogTs,
  },
  // —— Família / natureza ——
  {
    id: "partner-aquario",
    name: "AquaRio",
    slug: "aquario",
    defaultStrategy: "MANUAL",
    integration: { adapterKey: "manual", config: {} },
    commissionBps: 1500,
    contactEmail: "agentes@aquario.example",
    isActive: true,
    ...catalogTs,
  },
  {
    id: "partner-bioparque",
    name: "BioParque do Rio",
    slug: "bioparque",
    defaultStrategy: "MANUAL",
    integration: { adapterKey: "manual", config: {} },
    commissionBps: 1500,
    contactEmail: "ingressos@bioparque.example",
    isActive: true,
    ...catalogTs,
  },
  {
    id: "partner-jbrj",
    name: "Jardim Botânico do Rio",
    slug: "jardim-botanico",
    defaultStrategy: "API",
    integration: { adapterKey: "generic-rest", config: { baseUrl: "https://api.jbrj.example" } },
    commissionBps: 1000,
    contactEmail: "visitacao@jbrj.example",
    isActive: true,
    ...catalogTs,
  },
  // —— Museus & cultura ——
  {
    id: "partner-amanha",
    name: "Museu do Amanhã",
    slug: "museu-do-amanha",
    defaultStrategy: "MANUAL",
    integration: { adapterKey: "manual", config: {} },
    commissionBps: 1800,
    contactEmail: "bilheteria@amanha.example",
    isActive: true,
    ...catalogTs,
  },
  {
    id: "partner-mar",
    name: "Museu de Arte do Rio (MAR)",
    slug: "mar",
    defaultStrategy: "MANUAL",
    integration: { adapterKey: "manual", config: {} },
    commissionBps: 1200,
    contactEmail: "bilheteria@mar.example",
    isActive: true,
    ...catalogTs,
  },
  {
    id: "partner-theatro",
    name: "Theatro Municipal do Rio",
    slug: "theatro-municipal",
    defaultStrategy: "MANUAL",
    integration: { adapterKey: "manual", config: {} },
    commissionBps: 1000,
    contactEmail: "visitas@theatromunicipal.example",
    isActive: true,
    ...catalogTs,
  },
  // —— Esporte ——
  {
    id: "partner-maracana",
    name: "Maracanã Tour",
    slug: "maracana",
    defaultStrategy: "MANUAL",
    integration: { adapterKey: "manual", config: {} },
    commissionBps: 1300,
    contactEmail: "tour@maracana.example",
    isActive: true,
    ...catalogTs,
  },
  // —— Cinema ——
  {
    id: "partner-kinoplex",
    name: "Kinoplex",
    slug: "kinoplex",
    defaultStrategy: "API",
    integration: { adapterKey: "generic-rest", config: { baseUrl: "https://api.kinoplex.example" } },
    commissionBps: 800,
    contactEmail: "parceiros@kinoplex.example",
    isActive: true,
    ...catalogTs,
  },
];

export const catalogAttractions: Attraction[] = [
  // —— Ícones ——
  {
    id: "attr-corcovado",
    partnerId: "partner-corcovado",
    slug: "trem-do-corcovado-cristo-redentor",
    name: "Trem do Corcovado + Cristo Redentor",
    shortDescription:
      "Suba pela Floresta da Tijuca de trem até o Cristo Redentor, com horário marcado.",
    content: [
      {
        type: "paragraph",
        text: "A forma mais icônica de chegar ao Cristo Redentor: um passeio de trem pela Mata Atlântica com vistas panorâmicas e acesso ao mirante.",
      },
      { type: "heading", text: "O que esperar" },
      {
        type: "bullets",
        items: [
          "Trajeto panorâmico de cerca de 20 minutos",
          "Acesso ao mirante do Cristo Redentor",
          "Embarque com horário marcado (Cosme Velho)",
        ],
      },
    ],
    city: "Rio de Janeiro",
    heroImage: img("https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=1600", "Cristo Redentor"),
    gallery: [
      img("https://images.unsplash.com/photo-1516306580123-e6e52b1b7b5f?w=1200", "Vista do Rio"),
      img("https://images.unsplash.com/photo-1544989164-31dc3c645987?w=1200", "Floresta da Tijuca"),
    ],
    highlights: ["Horário marcado", "Emissão automática", "Inclui trem"],
    usageRules: [
      "Chegar 30 min antes do embarque",
      "Bilhete pessoal e intransferível",
      "Sujeito às condições climáticas",
    ],
    availability: {
      mode: "SCHEDULED",
      weekdays: [],
      defaultSlots: [
        { start: "08:00", capacity: 40 },
        { start: "10:00", capacity: 40 },
        { start: "13:00", capacity: 40 },
        { start: "15:00", capacity: 40 },
      ],
      blackoutDates: [],
      seasons: [],
      leadTimeHours: 3,
    },
    status: "PUBLISHED",
    ...catalogTs,
  },
  {
    id: "attr-pao",
    partnerId: "partner-pao",
    slug: "bondinho-pao-de-acucar",
    name: "Bondinho Pão de Açúcar",
    shortDescription:
      "Duas viagens de bondinho até o topo do Pão de Açúcar com vista de 360° da Baía de Guanabara.",
    content: [
      {
        type: "paragraph",
        text: "Um dos cartões-postais mais famosos do mundo: Morro da Urca e Pão de Açúcar em um único ingresso.",
      },
    ],
    city: "Rio de Janeiro",
    heroImage: img("https://images.unsplash.com/photo-1518639192441-8fce0a366e2e?w=1600", "Pão de Açúcar"),
    gallery: [],
    highlights: ["Data livre", "Dois mirantes", "Emissão automática"],
    usageRules: ["Válido para o dia escolhido", "Bilhete pessoal"],
    availability: {
      mode: "DATED",
      weekdays: [],
      defaultSlots: [],
      blackoutDates: [],
      seasons: [],
      leadTimeHours: 2,
    },
    status: "PUBLISHED",
    ...catalogTs,
  },
  {
    id: "attr-yupstar",
    partnerId: "partner-yupstar",
    slug: "yup-star-roda-gigante",
    name: "Yup Star — Roda Gigante",
    shortDescription:
      "A maior roda-gigante da América Latina, no Porto Maravilha, com vista aérea da orla e do Centro.",
    content: [
      {
        type: "paragraph",
        text: "Cabines climatizadas e vista panorâmica do Rio — experiência leve e ideal a qualquer hora do dia.",
      },
      {
        type: "bullets",
        items: [
          "Voucher com validade após a compra",
          "Localização no Porto Maravilha",
          "Boa opção para famílias e fotos",
        ],
      },
    ],
    city: "Rio de Janeiro",
    heroImage: img("https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1600", "Roda-gigante ao entardecer"),
    gallery: [],
    highlights: ["Sem horário marcado", "Válido por 30 dias", "Porto Maravilha"],
    usageRules: [
      "Voucher válido por 30 dias após a compra",
      "Crianças até 2 anos não pagam",
      "Apresentar documento para meia-entrada",
    ],
    availability: {
      mode: "OPEN",
      weekdays: [],
      defaultSlots: [],
      blackoutDates: [],
      seasons: [],
      leadTimeHours: 0,
      validityDays: 30,
    },
    status: "PUBLISHED",
    ...catalogTs,
  },
  // —— Família ——
  {
    id: "attr-aquario",
    partnerId: "partner-aquario",
    slug: "aquario-rio",
    name: "AquaRio — Aquário Marinho",
    shortDescription: "O maior aquário marinho da América do Sul, com data livre para visita.",
    content: [
      {
        type: "paragraph",
        text: "Mais de 8 mil animais de centenas de espécies, com túnel submarino e experiências para toda a família.",
      },
      {
        type: "bullets",
        items: [
          "Túnel submarino de 28 metros",
          "Data livre dentro da validade",
          "Ideal para famílias",
        ],
      },
    ],
    city: "Rio de Janeiro",
    heroImage: img("https://images.unsplash.com/photo-1544552866-d3ed42536cfd?w=1600", "Aquário"),
    gallery: [img("https://images.unsplash.com/photo-1560275619-4662e36fa65c?w=1200", "Peixes")],
    highlights: ["Data livre", "Emissão manual", "Voucher válido por 90 dias"],
    usageRules: [
      "Voucher válido por 90 dias",
      "Entrada sujeita à capacidade do dia",
      "Apresentar documento com foto",
    ],
    availability: {
      mode: "DATED",
      weekdays: [2, 3, 4, 5, 6, 0],
      defaultSlots: [],
      blackoutDates: ["2026-12-25"],
      seasons: [
        {
          id: "season-verao",
          label: "Alta temporada (verão)",
          from: "2026-12-15",
          to: "2027-02-28",
          priceAdjustmentBps: 1500,
        },
      ],
      leadTimeHours: 24,
      validityDays: 90,
    },
    status: "PUBLISHED",
    ...catalogTs,
  },
  {
    id: "attr-bioparque",
    partnerId: "partner-bioparque",
    slug: "bioparque-do-rio",
    name: "BioParque do Rio",
    shortDescription:
      "O antigo RioZoo repaginado na Quinta da Boa Vista — conservação, animais e contato com a natureza.",
    content: [
      {
        type: "paragraph",
        text: "Espaço de conservação na Quinta da Boa Vista, com habitats temáticos e programação educativa.",
      },
    ],
    city: "Rio de Janeiro",
    heroImage: img("https://images.unsplash.com/photo-1564349683136-77e08fdddb3e?w=1600", "Animais no parque"),
    gallery: [],
    highlights: ["Data livre", "Quinta da Boa Vista", "Família"],
    usageRules: [
      "Ingresso válido para o dia escolhido",
      "Meia-entrada mediante comprovação",
      "Fechado em datas de manutenção (consultar)",
    ],
    availability: {
      mode: "DATED",
      weekdays: [3, 4, 5, 6, 0],
      defaultSlots: [],
      blackoutDates: [],
      seasons: [
        {
          id: "season-alta-bio",
          label: "Alta temporada",
          from: "2026-12-15",
          to: "2027-02-28",
          priceAdjustmentBps: 1300,
        },
      ],
      leadTimeHours: 12,
    },
    status: "PUBLISHED",
    ...catalogTs,
  },
  {
    id: "attr-jardim",
    partnerId: "partner-jbrj",
    slug: "jardim-botanico",
    name: "Jardim Botânico do Rio",
    shortDescription:
      "Um dos jardins botânicos mais importantes do mundo — aleias, orquidário e Mata Atlântica no coração da Zona Sul.",
    content: [
      {
        type: "paragraph",
        text: "Fundado em 1808, o Jardim Botânico reúne coleções científicas, trilhas leves e o famoso Portal de Palmeiras.",
      },
    ],
    city: "Rio de Janeiro",
    heroImage: img("https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1600", "Jardim botânico"),
    gallery: [],
    highlights: ["Data livre", "Natureza", "Zona Sul"],
    usageRules: [
      "Tarifa residente Brasil mediante CPF",
      "Fechado em 25/12 e 01/01",
      "Horário reduzido em 24/12 e 31/12",
    ],
    availability: {
      mode: "DATED",
      weekdays: [],
      defaultSlots: [],
      blackoutDates: ["2026-12-25", "2027-01-01"],
      seasons: [],
      leadTimeHours: 2,
    },
    status: "PUBLISHED",
    ...catalogTs,
  },
  // —— Museus ——
  {
    id: "attr-amanha",
    partnerId: "partner-amanha",
    slug: "museu-do-amanha",
    name: "Museu do Amanhã",
    shortDescription: "Museu de ciências aplicadas no coração do Porto Maravilha.",
    content: [
      {
        type: "paragraph",
        text: "Experiência imersiva sobre as possibilidades de futuro para o planeta e a sociedade.",
      },
    ],
    city: "Rio de Janeiro",
    heroImage: img("https://images.unsplash.com/photo-1580537659466-0a9bfa916a54?w=1600", "Museu do Amanhã"),
    gallery: [],
    highlights: ["Horário agendado", "Porto Maravilha", "Interativo"],
    usageRules: ["Entrada no horário agendado", "Meia-entrada mediante comprovação"],
    availability: {
      mode: "SCHEDULED",
      weekdays: [2, 3, 4, 5, 6, 0],
      defaultSlots: [
        { start: "10:00", capacity: 60 },
        { start: "12:00", capacity: 60 },
        { start: "14:00", capacity: 60 },
        { start: "16:00", capacity: 60 },
      ],
      blackoutDates: [],
      seasons: [],
      leadTimeHours: 12,
    },
    status: "PUBLISHED",
    ...catalogTs,
  },
  {
    id: "attr-mar",
    partnerId: "partner-mar",
    slug: "museu-de-arte-do-rio",
    name: "Museu de Arte do Rio (MAR)",
    shortDescription:
      "Arte, história e cidade no Porto Maravilha — exposições permanentes e temporárias com vista para a Baía.",
    content: [
      {
        type: "paragraph",
        text: "O MAR conecta arte e vida urbana carioca, com programação cultural e Escola do Olhar.",
      },
    ],
    city: "Rio de Janeiro",
    heroImage: img("https://images.unsplash.com/photo-1577083552431-6e5fd01988ec?w=1600", "Museu de arte"),
    gallery: [],
    highlights: ["Cultura", "Porto Maravilha", "Entrada acessível"],
    usageRules: [
      "Fechado às quartas-feiras",
      "Gratuidade em dias promocionais (consultar)",
      "Meia mediante comprovação",
    ],
    availability: {
      mode: "DATED",
      weekdays: [0, 1, 2, 4, 5, 6],
      defaultSlots: [],
      blackoutDates: [],
      seasons: [],
      leadTimeHours: 4,
    },
    status: "PUBLISHED",
    ...catalogTs,
  },
  {
    id: "attr-theatro",
    partnerId: "partner-theatro",
    slug: "visita-theatro-municipal",
    name: "Visita guiada — Theatro Municipal",
    shortDescription:
      "Tour pelos bastidores e salões do Theatro Municipal, joia arquitetônica da Cinelândia.",
    content: [
      {
        type: "paragraph",
        text: "Visita guiada ao foyer, plateia e áreas históricas — experiência cultural em horário marcado.",
      },
    ],
    city: "Rio de Janeiro",
    heroImage: img("https://images.unsplash.com/photo-1503095396549-807759245b35?w=1600", "Teatro histórico"),
    gallery: [],
    highlights: ["Horário marcado", "Visita guiada", "Centro"],
    usageRules: [
      "Chegar 15 min antes",
      "Sujeito à programação de espetáculos",
      "Meia mediante comprovação",
    ],
    availability: {
      mode: "SCHEDULED",
      weekdays: [3, 4, 5, 6],
      defaultSlots: [
        { start: "11:00", capacity: 25 },
        { start: "14:00", capacity: 25 },
        { start: "16:00", capacity: 25 },
      ],
      blackoutDates: [],
      seasons: [],
      leadTimeHours: 24,
    },
    status: "PUBLISHED",
    ...catalogTs,
  },
  // —— Esporte ——
  {
    id: "attr-maracana",
    partnerId: "partner-maracana",
    slug: "maracana-tour",
    name: "Maracanã Tour",
    shortDescription:
      "Tour guiado pelo Maracanã: vestiários, zona mista, arquibancadas e campo — a casa do futebol brasileiro.",
    content: [
      {
        type: "paragraph",
        text: "Conheça os bastidores do estádio mais icônico do Brasil, com guia e acesso a áreas normalmente restritas.",
      },
    ],
    city: "Rio de Janeiro",
    heroImage: img("https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=1600", "Estádio de futebol"),
    gallery: [],
    highlights: ["Tour guiado", "Data livre", "Ícone do esporte"],
    usageRules: [
      "Horários podem mudar em dias de jogo",
      "Crianças até 2 anos não pagam",
      "Apresentar documento para tarifas promocionais",
    ],
    availability: {
      mode: "DATED",
      weekdays: [],
      defaultSlots: [],
      blackoutDates: [],
      seasons: [],
      leadTimeHours: 6,
    },
    status: "PUBLISHED",
    ...catalogTs,
  },
  // —— Cinema ——
  {
    id: "attr-kinoplex",
    partnerId: "partner-kinoplex",
    slug: "cinema-kinoplex",
    name: "Cinema Kinoplex — Sessão 2D",
    shortDescription:
      "Ingresso para sessão 2D em salas Kinoplex no Rio — escolha data e horário com antecedência.",
    content: [
      {
        type: "paragraph",
        text: "Garanta sua sessão em redes Kinoplex da cidade. Ideal para quem quer organizar lazer noturno ou em shopping sem surpresa na bilheteria.",
      },
      {
        type: "bullets",
        items: [
          "Sessões com horário marcado",
          "Tarifas de semana e fim de semana",
          "Meia-entrada mediante lei vigente",
        ],
      },
    ],
    city: "Rio de Janeiro",
    heroImage: img("https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1600", "Sala de cinema"),
    gallery: [],
    highlights: ["Sessão marcada", "2D", "Rede Kinoplex"],
    usageRules: [
      "Chegar com 15 min de antecedência",
      "Meia-entrada com documento",
      "Crianças até 2 anos e 11 meses no colo: isentos (política da rede)",
    ],
    availability: {
      mode: "SCHEDULED",
      weekdays: [],
      defaultSlots: [
        { start: "14:00", capacity: 80 },
        { start: "16:30", capacity: 80 },
        { start: "19:00", capacity: 100 },
        { start: "21:30", capacity: 100 },
      ],
      blackoutDates: [],
      seasons: [],
      leadTimeHours: 1,
    },
    status: "PUBLISHED",
    ...catalogTs,
  },
];

export const catalogTicketTypes: TicketType[] = [
  // Corcovado (~R$134 / meia ~R$70)
  {
    id: "tt-corcovado-inteira",
    attractionId: "attr-corcovado",
    name: "Inteira",
    price: money(13400),
    strategy: "API",
    partnerSkuCode: "CORC-FULL",
    maxPerOrder: 10,
    isActive: true,
    ...catalogTs,
  },
  {
    id: "tt-corcovado-meia",
    attractionId: "attr-corcovado",
    name: "Meia-entrada",
    description: "Crianças, idosos, estudantes e PcD (mediante comprovação).",
    price: money(7000),
    strategy: "API",
    partnerSkuCode: "CORC-HALF",
    maxPerOrder: 10,
    isActive: true,
    ...catalogTs,
  },
  // Pão (~R$160 brasileiros / meia ~R$102)
  {
    id: "tt-pao-inteira",
    attractionId: "attr-pao",
    name: "Inteira (Promo Brasil)",
    price: money(16000),
    strategy: "API",
    partnerSkuCode: "PAO-FULL",
    maxPerOrder: 10,
    isActive: true,
    ...catalogTs,
  },
  {
    id: "tt-pao-meia",
    attractionId: "attr-pao",
    name: "Meia-entrada",
    description: "Estudantes, 60+, PcD e crianças 3–12 (comprovação).",
    price: money(10200),
    strategy: "API",
    partnerSkuCode: "PAO-HALF",
    maxPerOrder: 10,
    isActive: true,
    ...catalogTs,
  },
  // Yup Star (~R$60 online / meia R$40)
  {
    id: "tt-yup-inteira",
    attractionId: "attr-yupstar",
    name: "Inteira (online)",
    price: money(5990),
    strategy: "MANUAL",
    maxPerOrder: 10,
    isActive: true,
    ...catalogTs,
  },
  {
    id: "tt-yup-meia",
    attractionId: "attr-yupstar",
    name: "Meia-entrada",
    price: money(3990),
    strategy: "MANUAL",
    maxPerOrder: 10,
    isActive: true,
    ...catalogTs,
  },
  // AquaRio (~R$123 / meia ~R$81)
  {
    id: "tt-aquario-inteira",
    attractionId: "attr-aquario",
    name: "Inteira",
    price: money(12300),
    strategy: "MANUAL",
    maxPerOrder: 8,
    isActive: true,
    ...catalogTs,
  },
  {
    id: "tt-aquario-meia",
    attractionId: "attr-aquario",
    name: "Meia-entrada",
    price: money(8100),
    strategy: "MANUAL",
    maxPerOrder: 8,
    isActive: true,
    ...catalogTs,
  },
  // BioParque (~R$69 / R$34,50)
  {
    id: "tt-bio-inteira",
    attractionId: "attr-bioparque",
    name: "Inteira",
    price: money(6900),
    strategy: "MANUAL",
    maxPerOrder: 10,
    isActive: true,
    ...catalogTs,
  },
  {
    id: "tt-bio-meia",
    attractionId: "attr-bioparque",
    name: "Meia-entrada",
    price: money(3450),
    strategy: "MANUAL",
    maxPerOrder: 10,
    isActive: true,
    ...catalogTs,
  },
  // Jardim Botânico (residente BR R$40 / estrangeiro R$80)
  {
    id: "tt-jardim-br",
    attractionId: "attr-jardim",
    name: "Residente no Brasil",
    description: "Mediante CPF / comprovação de residência no Brasil.",
    price: money(4000),
    strategy: "API",
    partnerSkuCode: "JBRJ-BR",
    maxPerOrder: 10,
    isActive: true,
    ...catalogTs,
  },
  {
    id: "tt-jardim-ext",
    attractionId: "attr-jardim",
    name: "Visitante estrangeiro",
    price: money(8000),
    strategy: "API",
    partnerSkuCode: "JBRJ-INT",
    maxPerOrder: 10,
    isActive: true,
    ...catalogTs,
  },
  // Museu do Amanhã (~R$40 / R$20)
  {
    id: "tt-amanha-inteira",
    attractionId: "attr-amanha",
    name: "Inteira",
    price: money(4000),
    strategy: "MANUAL",
    maxPerOrder: 10,
    isActive: true,
    ...catalogTs,
  },
  {
    id: "tt-amanha-meia",
    attractionId: "attr-amanha",
    name: "Meia-entrada",
    price: money(2000),
    strategy: "MANUAL",
    maxPerOrder: 10,
    isActive: true,
    ...catalogTs,
  },
  // MAR (~R$20 / R$10)
  {
    id: "tt-mar-inteira",
    attractionId: "attr-mar",
    name: "Inteira",
    price: money(2000),
    strategy: "MANUAL",
    maxPerOrder: 10,
    isActive: true,
    ...catalogTs,
  },
  {
    id: "tt-mar-meia",
    attractionId: "attr-mar",
    name: "Meia-entrada",
    price: money(1000),
    strategy: "MANUAL",
    maxPerOrder: 10,
    isActive: true,
    ...catalogTs,
  },
  // Theatro (~R$20 / R$10)
  {
    id: "tt-theatro-inteira",
    attractionId: "attr-theatro",
    name: "Inteira",
    price: money(2000),
    strategy: "MANUAL",
    maxPerOrder: 8,
    isActive: true,
    ...catalogTs,
  },
  {
    id: "tt-theatro-meia",
    attractionId: "attr-theatro",
    name: "Meia-entrada",
    price: money(1000),
    strategy: "MANUAL",
    maxPerOrder: 8,
    isActive: true,
    ...catalogTs,
  },
  // Maracanã (~R$94 / R$47)
  {
    id: "tt-maracana-inteira",
    attractionId: "attr-maracana",
    name: "Inteira",
    price: money(9400),
    strategy: "MANUAL",
    maxPerOrder: 10,
    isActive: true,
    ...catalogTs,
  },
  {
    id: "tt-maracana-meia",
    attractionId: "attr-maracana",
    name: "Meia-entrada",
    price: money(4700),
    strategy: "MANUAL",
    maxPerOrder: 10,
    isActive: true,
    ...catalogTs,
  },
  // Cinema (~R$39 fim de semana / meia R$19,50)
  {
    id: "tt-cine-inteira",
    attractionId: "attr-kinoplex",
    name: "Inteira 2D",
    description: "Referência quinta a domingo / feriados.",
    price: money(3900),
    strategy: "API",
    partnerSkuCode: "KPX-2D-FULL",
    maxPerOrder: 8,
    isActive: true,
    ...catalogTs,
  },
  {
    id: "tt-cine-meia",
    attractionId: "attr-kinoplex",
    name: "Meia-entrada 2D",
    price: money(1950),
    strategy: "API",
    partnerSkuCode: "KPX-2D-HALF",
    maxPerOrder: 8,
    isActive: true,
    ...catalogTs,
  },
];

function simpleProduct(opts: {
  id: string;
  attractionId: string;
  slug: string;
  name: string;
  tagline: string;
  category: NonNullable<Product["category"]>;
  heroImage: { url: string; alt: string };
  fromPrice: ReturnType<typeof money>;
  featured?: boolean;
}): Product {
  return {
    id: opts.id,
    type: "SIMPLE",
    slug: opts.slug,
    name: opts.name,
    tagline: opts.tagline,
    category: opts.category,
    heroImage: opts.heroImage,
    content: [],
    status: "PUBLISHED",
    attractionId: opts.attractionId,
    composition: null,
    fromPrice: opts.fromPrice,
    passportPrice: null,
    featured: opts.featured ?? false,
    ...catalogTs,
  };
}

export const catalogProducts: Product[] = [
  simpleProduct({
    id: "prod-corcovado",
    attractionId: "attr-corcovado",
    slug: "trem-do-corcovado-cristo-redentor",
    name: "Trem do Corcovado + Cristo Redentor",
    tagline: "Ícone • Horário marcado",
    category: "icone",
    heroImage: img("https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=1600", "Cristo Redentor"),
    fromPrice: money(7000),
    featured: true,
  }),
  simpleProduct({
    id: "prod-pao",
    attractionId: "attr-pao",
    slug: "bondinho-pao-de-acucar",
    name: "Bondinho Pão de Açúcar",
    tagline: "Ícone • Vista 360°",
    category: "icone",
    heroImage: img("https://images.unsplash.com/photo-1518639192441-8fce0a366e2e?w=1600", "Pão de Açúcar"),
    fromPrice: money(10200),
    featured: true,
  }),
  simpleProduct({
    id: "prod-yupstar",
    attractionId: "attr-yupstar",
    slug: "yup-star-roda-gigante",
    name: "Yup Star — Roda Gigante",
    tagline: "Ícone • Porto Maravilha",
    category: "icone",
    heroImage: img("https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1600", "Roda-gigante"),
    fromPrice: money(3990),
    featured: true,
  }),
  simpleProduct({
    id: "prod-aquario",
    attractionId: "attr-aquario",
    slug: "aquario-rio",
    name: "AquaRio — Aquário Marinho",
    tagline: "Família • Válido por 90 dias",
    category: "familia",
    heroImage: img("https://images.unsplash.com/photo-1544552866-d3ed42536cfd?w=1600", "Aquário"),
    fromPrice: money(8100),
    featured: true,
  }),
  simpleProduct({
    id: "prod-bioparque",
    attractionId: "attr-bioparque",
    slug: "bioparque-do-rio",
    name: "BioParque do Rio",
    tagline: "Família • Quinta da Boa Vista",
    category: "familia",
    heroImage: img("https://images.unsplash.com/photo-1564349683136-77e08fdddb3e?w=1600", "BioParque"),
    fromPrice: money(3450),
  }),
  simpleProduct({
    id: "prod-jardim",
    attractionId: "attr-jardim",
    slug: "jardim-botanico",
    name: "Jardim Botânico do Rio",
    tagline: "Família • Natureza na Zona Sul",
    category: "familia",
    heroImage: img("https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1600", "Jardim Botânico"),
    fromPrice: money(4000),
  }),
  simpleProduct({
    id: "prod-amanha",
    attractionId: "attr-amanha",
    slug: "museu-do-amanha",
    name: "Museu do Amanhã",
    tagline: "Museu • Horário agendado",
    category: "museu",
    heroImage: img("https://images.unsplash.com/photo-1580537659466-0a9bfa916a54?w=1600", "Museu do Amanhã"),
    fromPrice: money(2000),
    featured: true,
  }),
  simpleProduct({
    id: "prod-mar",
    attractionId: "attr-mar",
    slug: "museu-de-arte-do-rio",
    name: "Museu de Arte do Rio (MAR)",
    tagline: "Museu • Porto Maravilha",
    category: "museu",
    heroImage: img("https://images.unsplash.com/photo-1577083552431-6e5fd01988ec?w=1600", "MAR"),
    fromPrice: money(1000),
  }),
  simpleProduct({
    id: "prod-theatro",
    attractionId: "attr-theatro",
    slug: "visita-theatro-municipal",
    name: "Visita guiada — Theatro Municipal",
    tagline: "Museu • Visita guiada",
    category: "museu",
    heroImage: img("https://images.unsplash.com/photo-1503095396549-807759245b35?w=1600", "Theatro Municipal"),
    fromPrice: money(1000),
  }),
  simpleProduct({
    id: "prod-maracana",
    attractionId: "attr-maracana",
    slug: "maracana-tour",
    name: "Maracanã Tour",
    tagline: "Esporte • Tour guiado",
    category: "esporte",
    heroImage: img("https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=1600", "Maracanã"),
    fromPrice: money(4700),
  }),
  simpleProduct({
    id: "prod-kinoplex",
    attractionId: "attr-kinoplex",
    slug: "cinema-kinoplex",
    name: "Cinema Kinoplex — Sessão 2D",
    tagline: "Cinema • Sessão marcada",
    category: "cinema",
    heroImage: img("https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1600", "Cinema"),
    fromPrice: money(1950),
  }),
  {
    id: "prod-passaporte-rio",
    type: "PASSPORT",
    slug: "passaporte-rio-essencial",
    name: "Passaporte Rio Essencial",
    tagline: "3 ícones em um único pedido",
    category: "passaporte",
    heroImage: img("https://images.unsplash.com/photo-1516306580123-e6e52b1b7b5f?w=1600", "Rio de Janeiro"),
    content: [
      {
        type: "paragraph",
        text: "Organize o essencial do Rio em um só passaporte: Cristo Redentor, Pão de Açúcar e AquaRio — com regras claras por atração e uma compra centralizada.",
      },
    ],
    status: "PUBLISHED",
    attractionId: null,
    composition: {
      items: [
        {
          id: "pi-1",
          attractionId: "attr-corcovado",
          ticketTypeId: "tt-corcovado-inteira",
          quantity: 1,
          required: true,
          order: 1,
        },
        {
          id: "pi-2",
          attractionId: "attr-pao",
          ticketTypeId: "tt-pao-inteira",
          quantity: 1,
          required: true,
          order: 2,
        },
        {
          id: "pi-3",
          attractionId: "attr-aquario",
          ticketTypeId: "tt-aquario-inteira",
          quantity: 1,
          required: true,
          order: 3,
        },
      ],
    },
    fromPrice: money(35000),
    passportPrice: money(35000),
    featured: true,
    ...catalogTs,
  },
  {
    id: "prod-passaporte-familia",
    type: "PASSPORT",
    slug: "passaporte-rio-familia",
    name: "Passaporte Rio Família",
    tagline: "AquaRio + BioParque + Yup Star",
    category: "passaporte",
    heroImage: img("https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=1600", "Família viajando"),
    content: [
      {
        type: "paragraph",
        text: "Roteiro leve para famílias: aquário, parque e roda-gigante — tudo em uma compra só.",
      },
    ],
    status: "PUBLISHED",
    attractionId: null,
    composition: {
      items: [
        {
          id: "pi-f1",
          attractionId: "attr-aquario",
          ticketTypeId: "tt-aquario-inteira",
          quantity: 1,
          required: true,
          order: 1,
        },
        {
          id: "pi-f2",
          attractionId: "attr-bioparque",
          ticketTypeId: "tt-bio-inteira",
          quantity: 1,
          required: true,
          order: 2,
        },
        {
          id: "pi-f3",
          attractionId: "attr-yupstar",
          ticketTypeId: "tt-yup-inteira",
          quantity: 1,
          required: true,
          order: 3,
        },
      ],
    },
    fromPrice: money(22000),
    passportPrice: money(22000),
    featured: true,
    ...catalogTs,
  },
];
