import type { Site } from "@/features/tenant/types";
import type { Partner } from "@/features/partners/types";
import type { Attraction, TicketType } from "@/features/attractions/types";
import type { Product } from "@/features/catalog/types";
import type { Fulfillment } from "@/features/fulfillment/types";
import { money } from "@/features/shared/types";

const NOW = "2026-01-01T00:00:00.000Z";
const ts = { createdAt: NOW, updatedAt: NOW };

const img = (url: string, alt: string) => ({ url, alt });

export const seedPartners: Partner[] = [
  {
    id: "partner-corcovado",
    name: "Trem do Corcovado",
    slug: "trem-do-corcovado",
    defaultStrategy: "API",
    integration: { adapterKey: "generic-rest", config: { baseUrl: "https://api.parceiro.example" } },
    commissionBps: 1200,
    contactEmail: "operacao@corcovado.example",
    isActive: true,
    ...ts,
  },
  {
    id: "partner-aquario",
    name: "AquaRio",
    slug: "aquario",
    defaultStrategy: "MANUAL",
    integration: { adapterKey: "manual", config: {} },
    commissionBps: 1500,
    contactEmail: "agentes@aquario.example",
    isActive: true,
    ...ts,
  },
  {
    id: "partner-pao",
    name: "Bondinho Pão de Açúcar",
    slug: "pao-de-acucar",
    defaultStrategy: "API",
    integration: { adapterKey: "generic-rest", config: { baseUrl: "https://api.bondinho.example" } },
    commissionBps: 1000,
    contactEmail: "parceiros@bondinho.example",
    isActive: true,
    ...ts,
  },
  {
    id: "partner-amanha",
    name: "Museu do Amanhã",
    slug: "museu-do-amanha",
    defaultStrategy: "MANUAL",
    integration: { adapterKey: "manual", config: {} },
    commissionBps: 1800,
    contactEmail: "bilheteria@amanha.example",
    isActive: true,
    ...ts,
  },
];

export const seedAttractions: Attraction[] = [
  {
    id: "attr-corcovado",
    partnerId: "partner-corcovado",
    slug: "trem-do-corcovado-cristo-redentor",
    name: "Trem do Corcovado + Cristo Redentor",
    shortDescription:
      "Suba pela Floresta da Tijuca de trem até o Cristo Redentor, com horário marcado.",
    content: [
      { type: "paragraph", text: "A forma mais icônica de chegar ao Cristo Redentor: um passeio de trem pela mata atlântica com vistas deslumbrantes." },
      { type: "heading", text: "O que esperar" },
      { type: "bullets", items: ["Trajeto panorâmico de ~20 minutos", "Acesso ao mirante do Cristo Redentor", "Embarque com horário marcado"] },
    ],
    city: "Rio de Janeiro",
    heroImage: img("https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=1600", "Cristo Redentor"),
    gallery: [
      img("https://images.unsplash.com/photo-1516306580123-e6e52b1b7b5f?w=1200", "Vista do Rio"),
      img("https://images.unsplash.com/photo-1544989164-31dc3c645987?w=1200", "Floresta da Tijuca"),
    ],
    highlights: ["Horário marcado", "Emissão automática", "Guia opcional"],
    usageRules: ["Chegar 30 min antes do embarque", "Bilhete pessoal e intransferível", "Sujeito às condições climáticas"],
    availability: {
      mode: "SCHEDULED",
      weekdays: [],
      defaultSlots: [
        { start: "08:00", capacity: 40 },
        { start: "10:00", capacity: 40 },
        { start: "13:00", capacity: 40 },
        { start: "15:00", capacity: 40 },
      ],
      blackoutDates: [],
      seasons: [],
      leadTimeHours: 3,
    },
    status: "PUBLISHED",
    ...ts,
  },
  {
    id: "attr-aquario",
    partnerId: "partner-aquario",
    slug: "aquario-rio",
    name: "AquaRio — Aquário Marinho",
    shortDescription: "O maior aquário marinho da América do Sul, com data livre para visita.",
    content: [
      { type: "paragraph", text: "Mais de 8 mil animais de 350 espécies em um dos maiores aquários da América Latina." },
      { type: "bullets", items: ["Túnel submarino de 28 metros", "Data livre — visite quando quiser dentro da validade", "Ideal para famílias"] },
    ],
    city: "Rio de Janeiro",
    heroImage: img("https://images.unsplash.com/photo-1544552866-d3ed42536cfd?w=1600", "Aquário"),
    gallery: [img("https://images.unsplash.com/photo-1560275619-4662e36fa65c?w=1200", "Peixes")],
    highlights: ["Data livre", "Emissão manual", "Voucher válido por 90 dias"],
    usageRules: ["Voucher válido por 90 dias", "Entrada sujeita à capacidade do dia", "Apresentar documento com foto"],
    availability: {
      mode: "DATED",
      weekdays: [2, 3, 4, 5, 6, 0],
      defaultSlots: [],
      blackoutDates: ["2026-12-25"],
      seasons: [
        { id: "season-verao", label: "Alta temporada (verão)", from: "2026-12-15", to: "2027-02-28", priceAdjustmentBps: 1500 },
      ],
      leadTimeHours: 24,
      validityDays: 90,
    },
    status: "PUBLISHED",
    ...ts,
  },
  {
    id: "attr-pao",
    partnerId: "partner-pao",
    slug: "bondinho-pao-de-acucar",
    name: "Bondinho Pão de Açúcar",
    shortDescription: "Duas viagens de bondinho até o topo do Pão de Açúcar com vista de 360°.",
    content: [{ type: "paragraph", text: "Um dos cartões-postais mais famosos do mundo, com vista panorâmica da Baía de Guanabara." }],
    city: "Rio de Janeiro",
    heroImage: img("https://images.unsplash.com/photo-1518639192441-8fce0a366e2e?w=1600", "Pão de Açúcar"),
    gallery: [],
    highlights: ["Data livre", "Emissão automática", "Acesso aos dois morros"],
    usageRules: ["Válido para o dia escolhido", "Bilhete pessoal"],
    availability: {
      mode: "DATED",
      weekdays: [],
      defaultSlots: [],
      blackoutDates: [],
      seasons: [],
      leadTimeHours: 2,
    },
    status: "PUBLISHED",
    ...ts,
  },
  {
    id: "attr-amanha",
    partnerId: "partner-amanha",
    slug: "museu-do-amanha",
    name: "Museu do Amanhã",
    shortDescription: "Museu de ciências aplicadas no coração do Porto Maravilha.",
    content: [{ type: "paragraph", text: "Uma experiência imersiva sobre as possibilidades de futuro para o planeta e a sociedade." }],
    city: "Rio de Janeiro",
    heroImage: img("https://images.unsplash.com/photo-1580537659466-0a9bfa916a54?w=1600", "Museu do Amanhã"),
    gallery: [],
    highlights: ["Data marcada", "Emissão manual", "Exposições interativas"],
    usageRules: ["Entrada no horário agendado", "Meia-entrada mediante comprovação"],
    availability: {
      mode: "SCHEDULED",
      weekdays: [2, 3, 4, 5, 6, 0],
      defaultSlots: [
        { start: "10:00", capacity: 60 },
        { start: "14:00", capacity: 60 },
      ],
      blackoutDates: [],
      seasons: [],
      leadTimeHours: 12,
    },
    status: "PUBLISHED",
    ...ts,
  },
];

export const seedTicketTypes: TicketType[] = [
  { id: "tt-corcovado-inteira", attractionId: "attr-corcovado", name: "Inteira", price: money(11500), strategy: "API", partnerSkuCode: "CORC-FULL", maxPerOrder: 10, isActive: true, ...ts },
  { id: "tt-corcovado-meia", attractionId: "attr-corcovado", name: "Meia-entrada", description: "Estudantes, idosos e crianças (mediante comprovação).", price: money(5750), strategy: "API", partnerSkuCode: "CORC-HALF", maxPerOrder: 10, isActive: true, ...ts },
  { id: "tt-aquario-inteira", attractionId: "attr-aquario", name: "Inteira", price: money(13000), strategy: "MANUAL", maxPerOrder: 8, isActive: true, ...ts },
  { id: "tt-aquario-meia", attractionId: "attr-aquario", name: "Meia-entrada", price: money(6500), strategy: "MANUAL", maxPerOrder: 8, isActive: true, ...ts },
  { id: "tt-pao-inteira", attractionId: "attr-pao", name: "Inteira", price: money(16000), strategy: "API", partnerSkuCode: "PAO-FULL", maxPerOrder: 10, isActive: true, ...ts },
  { id: "tt-amanha-inteira", attractionId: "attr-amanha", name: "Inteira", price: money(3000), strategy: "MANUAL", maxPerOrder: 10, isActive: true, ...ts },
];

export const seedProducts: Product[] = [
  {
    id: "prod-corcovado",
    type: "SIMPLE",
    slug: "trem-do-corcovado-cristo-redentor",
    name: "Trem do Corcovado + Cristo Redentor",
    tagline: "Horário marcado • Emissão imediata",
    heroImage: img("https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=1600", "Cristo Redentor"),
    content: [],
    status: "PUBLISHED",
    attractionId: "attr-corcovado",
    composition: null,
    fromPrice: money(5750),
    passportPrice: null,
    featured: true,
    ...ts,
  },
  {
    id: "prod-aquario",
    type: "SIMPLE",
    slug: "aquario-rio",
    name: "AquaRio — Aquário Marinho",
    tagline: "Data livre • Válido por 90 dias",
    heroImage: img("https://images.unsplash.com/photo-1544552866-d3ed42536cfd?w=1600", "Aquário"),
    content: [],
    status: "PUBLISHED",
    attractionId: "attr-aquario",
    composition: null,
    fromPrice: money(6500),
    passportPrice: null,
    featured: true,
    ...ts,
  },
  {
    id: "prod-pao",
    type: "SIMPLE",
    slug: "bondinho-pao-de-acucar",
    name: "Bondinho Pão de Açúcar",
    tagline: "Data livre • Vista 360°",
    heroImage: img("https://images.unsplash.com/photo-1518639192441-8fce0a366e2e?w=1600", "Pão de Açúcar"),
    content: [],
    status: "PUBLISHED",
    attractionId: "attr-pao",
    composition: null,
    fromPrice: money(16000),
    passportPrice: null,
    featured: false,
    ...ts,
  },
  {
    id: "prod-passaporte-rio",
    type: "PASSPORT",
    slug: "passaporte-rio-essencial",
    name: "Passaporte Rio Essencial",
    tagline: "3 atrações icônicas em um único produto",
    heroImage: img("https://images.unsplash.com/photo-1516306580123-e6e52b1b7b5f?w=1600", "Rio de Janeiro"),
    content: [
      { type: "paragraph", text: "Viva o melhor do Rio em um único passaporte: Cristo Redentor, Pão de Açúcar e AquaRio — com regras e emissões diferentes, mas uma compra só." },
    ],
    status: "PUBLISHED",
    attractionId: null,
    composition: {
      items: [
        { id: "pi-1", attractionId: "attr-corcovado", ticketTypeId: "tt-corcovado-inteira", quantity: 1, required: true, order: 1 },
        { id: "pi-2", attractionId: "attr-pao", ticketTypeId: "tt-pao-inteira", quantity: 1, required: true, order: 2 },
        { id: "pi-3", attractionId: "attr-aquario", ticketTypeId: "tt-aquario-inteira", quantity: 1, required: true, order: 3 },
      ],
    },
    fromPrice: money(35000),
    passportPrice: money(35000),
    featured: true,
    ...ts,
  },
];

export const seedFulfillments: Fulfillment[] = [
  {
    id: "ful-001",
    orderId: "ord-1042",
    orderItemId: "oi-1",
    siteId: "onerio",
    partnerId: "partner-aquario",
    attractionId: "attr-aquario",
    ticketTypeId: "tt-aquario-inteira",
    strategy: "MANUAL",
    status: "PENDING",
    snapshot: {
      attractionName: "AquaRio — Aquário Marinho",
      partnerName: "AquaRio",
      ticketTypeName: "Inteira",
      quantity: 2,
      visitDate: "2026-02-14",
      visitSlot: null,
      customerName: "Marina Souza",
      customerEmail: "marina.souza@email.com",
      customerDocument: "123.456.789-00",
    },
    ticketAssets: [],
    ...ts,
  },
  {
    id: "ful-002",
    orderId: "ord-1043",
    orderItemId: "oi-2",
    siteId: "onerio",
    partnerId: "partner-amanha",
    attractionId: "attr-amanha",
    ticketTypeId: "tt-amanha-inteira",
    strategy: "MANUAL",
    status: "PROCESSING",
    snapshot: {
      attractionName: "Museu do Amanhã",
      partnerName: "Museu do Amanhã",
      ticketTypeName: "Inteira",
      quantity: 4,
      visitDate: "2026-02-10",
      visitSlot: "14:00",
      customerName: "João Pereira",
      customerEmail: "joao.pereira@email.com",
    },
    ticketAssets: [],
    handledByUid: "operador-1",
    ...ts,
  },
  {
    id: "ful-003",
    orderId: "ord-1044",
    orderItemId: "oi-3",
    siteId: "onerio",
    partnerId: "partner-aquario",
    attractionId: "attr-aquario",
    ticketTypeId: "tt-aquario-meia",
    strategy: "MANUAL",
    status: "ISSUED",
    snapshot: {
      attractionName: "AquaRio — Aquário Marinho",
      partnerName: "AquaRio",
      ticketTypeName: "Meia-entrada",
      quantity: 1,
      visitDate: "2026-02-08",
      visitSlot: null,
      customerName: "Ana Lima",
      customerEmail: "ana.lima@email.com",
    },
    ticketAssets: [{ id: "asset-1", url: "#", fileName: "aquario-ana.pdf", code: "AQ-88213" }],
    ...ts,
  },
];

export const seedSites: Site[] = [
  {
    id: "onerio",
    slug: "onerio",
    name: "OneRio",
    domains: ["onerio.com", "www.onerio.com", "localhost"],
    theme: {
      brand: "13 26 38",
      brandFg: "255 255 255",
      brandMuted: "233 122 60",
      logoUrl: "",
    },
    attractionIds: null,
    partnerId: null,
    status: "PUBLISHED",
    contactEmail: "contato@onerio.com",
    supportPhone: "+55 21 90000-0000",
    ...ts,
  },
  {
    id: "site-aquario",
    slug: "aquario",
    name: "AquaRio Ingressos",
    domains: ["ingressos.aquario.example", "aquario.localhost"],
    theme: {
      brand: "12 74 110",
      brandFg: "255 255 255",
      brandMuted: "56 189 248",
      logoUrl: "",
    },
    attractionIds: ["attr-aquario"],
    partnerId: "partner-aquario",
    status: "PUBLISHED",
    contactEmail: "ingressos@aquario.example",
    ...ts,
  },
];
